all:
	mkdir -p class/

	# Producers and Consumers
	javac -d class/ -sourcepath src/Producers-Consumers src/Producers-Consumers/Dropbox.java
	javac -d class/ -sourcepath src/Producers-Consumers src/Producers-Consumers/Consumer.java
	javac -d class/ -sourcepath src/Producers-Consumers src/Producers-Consumers/Producer.java
	javac -d class/ -sourcepath src/Producers-Consumers src/Producers-Consumers/ProducerConsumerExample.java
	#
	# Readers and Writers
	javac -d class/ -sourcepath src/Readers-Writers src/Readers-Writers/ISharedResource.java
	javac -d class/ -sourcepath src/Readers-Writers src/Readers-Writers/SharedMonitor.java
	javac -d class/ -sourcepath src/Readers-Writers src/Readers-Writers/SharedSemaphore.java
	javac -d class/ -sourcepath src/Readers-Writers src/Readers-Writers/Writer.java
	javac -d class/ -sourcepath src/Readers-Writers src/Readers-Writers/Reader.java
	javac -d class/ -sourcepath src/Readers-Writers src/Readers-Writers/ReaderWriterMonitorExample.java
	javac -d class/ -sourcepath src/Readers-Writers src/Readers-Writers/ReaderWriterSemaphoreExample.java
	#
	# Philosophers
	javac -d class/ -sourcepath src/Philosophers src/Philosophers/IChopsticks.java
	javac -d class/ -sourcepath src/Philosophers src/Philosophers/ChopsticksMonitor.java
	javac -d class/ -sourcepath src/Philosophers src/Philosophers/ChopsticksSemaphore.java
	javac -d class/ -sourcepath src/Philosophers src/Philosophers/ChopsticksView.java
	javac -d class/ -sourcepath src/Philosophers src/Philosophers/Philosopher.java
	javac -d class/ -sourcepath src/Philosophers src/Philosophers/PhilosophersMonitorExample.java
	javac -d class/ -sourcepath src/Philosophers src/Philosophers/PhilosophersSemaphoreExample.java