all:
	mkdir class/
	javac -d class/ -sourcepath src/ src/Inbox.java
	javac -d class/ -sourcepath src/ src/Database.java
	javac -d class/ -sourcepath src/ src/DateClient.java
	javac -d class/ -sourcepath src/ src/DateServer.java