all:
	mkdir -p class/
	javac -d class/ -sourcepath src/ src/Process.java
	javac -d class/ -sourcepath src/ src/SystemState.java
	javac -d class/ -sourcepath src/ src/Safety.java
	javac -d class/ -sourcepath src/ src/Detection.java
	javac -d class/ -sourcepath src/ src/Avoid.java