all:
	mkdir -p class/
	javac -d class/ -sourcepath src/ src/Process.java
	javac -d class/ -sourcepath src/ src/Statistics.java
	javac -d class/ -sourcepath src/ src/TimeSlot.java
	javac -d class/ -sourcepath src/ src/Scheduler.java
	javac -d class/ -sourcepath src/ src/SchedulerFCFS.java
	javac -d class/ -sourcepath src/ src/SchedulerSJF.java
	javac -d class/ -sourcepath src/ src/SchedulerSJFP.java
	javac -d class/ -sourcepath src/ src/SchedulerPriority.java
	javac -d class/ -sourcepath src/ src/SchedulerPriorityP.java
	javac -d class/ -sourcepath src/ src/escalonador.java