all:
	mkdir -p class/
	javac -d class/ -sourcepath src/ src/Process.java
	javac -d class/ -sourcepath src/ src/Statistics.java
	javac -d class/ -sourcepath src/ src/TimeSlot.java
	javac -d class/ -sourcepath src/ src/Scheduler.java
	javac -d class/ -sourcepath src/ src/SchedulerFCFS.java
	javac -d class/ -sourcepath src/ src/SchedulerRR.java
	javac -d class/ -sourcepath src/ src/SchedulerRank.java
	javac -d class/ -sourcepath src/ src/SchedulerRankSJF.java
	javac -d class/ -sourcepath src/ src/SchedulerRankPriority.java
	javac -d class/ -sourcepath src/ src/SchedulerRankPreemp.java
	javac -d class/ -sourcepath src/ src/SchedulerRankPreempSJF.java
	javac -d class/ -sourcepath src/ src/SchedulerRankPreempPriority.java
	javac -d class/ -sourcepath src/ src/escalonador.java