all:
	javac -d class/ -cp class/ -sourcepath src/operations src/operations/ICalc.java
	javac -d class/ -cp class/ -sourcepath src/operations src/operations/Calc.java
	javac -d class/ -cp class/ -sourcepath src/operations src/operations/Inbox.java
	javac -d class/ -cp class/ -sourcepath src/operations src/operations/Database.java
	javac -d class/ -cp class/ -sourcepath src/server     src/server/Server.java
	javac -d class/ -cp class/ -sourcepath src/client     src/client/Client.java
