all:
	javac -d class/ -cp class/ -sourcepath src/server src/server/ICalcServer.java
	javac -d class/ -cp class/ -sourcepath src/server src/server/CalcServer.java
	javac -d class/ -cp class/ -sourcepath src/client src/client/CalcClient.java
