all:
	javac -d class/ -cp class/ -sourcepath src/server src/server/ICalc.java
	javac -d class/ -cp class/ -sourcepath src/server src/server/Calc.java
	javac -d class/ -cp class/ -sourcepath src/server src/server/Server.java
	javac -d class/ -cp class/ -sourcepath src/client src/client/Client.java
